server:
  port: 8081

spring:
  application:
    name: MCIROSERVICE-ONE
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
eureka:
  client:
    serviceUrl:
      healthcheck:
        enabled: true
      defaultZone: http://localhost:8761/eureka/

