server:
  port: 8081

spring:
  application:
    name: MCIROSERVICE-ONE
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    initialize: true
    data: schema.sql
    schema: schema.sql
  h2:
    console.enabled: true
    console.path: /h2-console

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
eureka:
  client:
    serviceUrl:
      healthcheck:
        enabled: true
      defaultZone: http://localhost:8761/eureka/

